name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E tests
    runs-on: ubuntu-latest

    services:
      database:
        image: bitnami/postgresql
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: api-with-solid

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run E2E tests
        run: bun run test:e2e
        env:
          JWT_SECRET: testing
          BASE_URL: http://localhost:3333
          DATABASE_URL: postgresql://docker:docker@localhost:5432/api-with-solid?schema=public
